# Generated by Django 5.2.8 on 2025-11-25 07:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Unique ID (Ticket ID, M-Pesa Ref)', max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit (M-Pesa)'), ('WITHDRAWAL', 'Withdrawal (B2C)'), ('TICKET_SALE', 'Ticket Sale Split'), ('FEE', 'Service Fee')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit (-)'), ('CREDIT', 'Credit (+)')], max_length=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(choices=[('MASTER', 'Master Liquidity (Physical Bank)'), ('REVENUE', 'Yadi Revenue (Fees)'), ('ORGANIZER', 'Organizer Wallet'), ('CUSTOMER', 'Customer Wallet')], default='ORGANIZER', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
            ],
        ),
    ]
