# Generated by Django 5.2.8 on 2025-11-25 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_txs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scheduled_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_APPROVAL', 'Pending Admin Approval'), ('APPROVED', 'Approved (Waiting Release)'), ('ON_HOLD', 'Frozen / Under Investigation'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected (Refunded)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('MASTER', 'Master Liquidity (Physical Bank)'), ('REVENUE', 'Yadi Revenue'), ('ORGANIZER', 'Organizer Wallet'), ('SUSPENSE', 'Payout Clearing (Suspense)'), ('CUSTOMER', 'Customer Wallet')], default='ORGANIZER', max_length=20),
        ),
    ]
