# Generated by Django 5.2.8 on 2025-11-27 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_approved_at_transaction_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('network_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Default wallet for deposits'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='label',
            field=models.CharField(default='Main Wallet', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit (M-Pesa)'), ('WITHDRAWAL', 'Withdrawal (B2C)'), ('TICKET_SALE', 'Ticket Sale Split'), ('FEE', 'Service Fee'), ('TRANSFER', 'Internal Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('CUSTOMER', 'Personal Wallet'), ('ORGANIZER', 'Business Wallet'), ('MASTER', 'Liquidity Float (Paybill)'), ('SETTLEMENT', 'Settlement (Incoming)'), ('REVENUE', 'Yadi Revenue (Profit)'), ('SUSPENSE', 'Suspense (Held Funds)'), ('RESERVE', 'Reserve (Bank Vault)')], default='ORGANIZER', max_length=20),
        ),
    ]
