# Generated by Django 5.2.8 on 2025-11-27 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Percentage taken from Ticket Sales (e.g. 4.00)', max_digits=5),
        ),
    ]
